all:
  hosts:
    moodlebox:
<<<<<<< HEAD
      ansible_host: '192.168.0.6'
=======
      ansible_host: '192.168.1.226'
>>>>>>> 709b33ad685a4046f787aed95da5f0d8c04a66a2
      ansible_user: 'pi'
      ansible_password: 'bananapi'